name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  python-code-quality:
    name: Python Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run isort
        run: |
          echo "Running isort..."
          uv run isort . --check-only --diff
        continue-on-error: false

      - name: Run Black
        run: |
          echo "Running Black..."
          uv run black . --check --diff
        continue-on-error: false

      - name: Run Flake8
        run: |
          echo "Running Flake8..."
          uv run flake8 .
        continue-on-error: false

      - name: Run Mypy
        run: |
          echo "Running Mypy..."
          uv run mypy .
        continue-on-error: false

      - name: Code Quality Summary
        if: always()
        run: |
          echo "🎯 Code Quality Check Complete"
          echo "All static analysis tools have been executed."

  tests:
    runs-on: ubuntu-latest
    needs: python-code-quality

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: |
          echo "Running tests..."
          uv run pytest tests/ -v --tb=short
        continue-on-error: false

      - name: Test Summary
        if: always()
        run: |
          echo "🧪 Test Execution Complete"
